apiVersion: 1

datasources:
  - name: CrateDB
    type: postgres
    access: proxy
    url: cratedb:5432
    database: doc
    user: crate
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false