apiVersion: 1

datasources:
  - name: CrateDB
    type: postgres
    access: proxy
    url: cratedb:5432
    database: crate
    user: crate
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: false